# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ConfettiExample' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ConfettiExample
  pod 'ConfettiView', :path => '../'
  
  target 'ConfettiExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ConfettiExampleUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
